### Data Umbrella PyMC Open Source Working Sessions
#### July to August, 2022

#### Notes
- Input data: `'../data/data_derived/derived_geocodes_pymc.csv'`
- Output data: `'../data/data_derived/pymc_2022_derived.csv'`

---

In [1]:
import pandas as pd

In [2]:
from datetime import date

today = date.today()

print("Today's date:", today)

Today's date: 2022-08-26

In [3]:
# Finalize dataset
df_use = pd.read_csv('../data/data_derived/derived_geocodes_pymc.csv', index_col=False)  

df_use.head(3)

,location,continent_o,country_o,iso_alpha,iso_num,lat,lng,timestamp,city,state-province,...,prior_os_pr,git,prog_langs,python_experience,used_pymc,pymc_repo_familiar,why_in_sprint,prep_work,primary_spoken_language,language_translation
0,Rochester USA,North America,United States,USD,840,43.157285,-77.615214,6/13/2022 18:54:55,Rochester,New York,...,Yes,"comfortable submitting a PR, comfortable setti...","Python, C+ / C++, Java",Advanced,I am not at all familiar with PyMC.,"I am familiar, I have looked at the codebase.","Looking to grow my skills as a developer, and ...",NaN,English,No
1,Rochester USA,North America,United States,USD,840,43.157285,-77.615214,7/7/2022 10:47:41,Rochester,New York,...,No,no experience with Git,"Python, R, SQL",Beginner,I am not at all familiar with PyMC.,I am not at all familiar with this library.,Open source data is very valuable and I'd like...,Not sure,"English, ASL",No
2,New York USA,North America,United States,USD,840,40.712728,-74.006015,6/13/2022 19:56:59,New York,New York,...,No,comfortable setting up virtual environment,Python,Intermediate,I am not at all familiar with PyMC.,I am not at all familiar with this library.,gain experience and learn,Yes,English,No

In [4]:
df_use.columns

Index(['location', 'continent_o', 'country_o', 'iso_alpha', 'iso_num', 'lat',
       'lng', 'timestamp', 'city', 'state-province', 'country', 'gender',
       'pronouns', 'pre_oh', 'session_1', 'session_2', 'session_3', 'post_oh',
       'total_events', 'submitted_pr', 'joined_discord', 'role', 'urp',
       'sessions', 'learn_of_sprint', 'prior_sprints', 'os_experience',
       'prior_os_pr', 'git', 'prog_langs', 'python_experience', 'used_pymc',
       'pymc_repo_familiar', 'why_in_sprint', 'prep_work',
       'primary_spoken_language', 'language_translation'],
      dtype='object')

In [5]:
df_use['count_rows']=1
df_use['count']=1

df_use['status_n']= 0
#df_use['status_n'].mask(df_use['total_events'] == 0, 0, inplace=True)
df_use['status_n'].mask(df_use['total_events'] >= 1, 1, inplace=True)

df_use['status_c']='x'
df_use['status_c'].mask(df_use['total_events'] == 0, 'Did Not Attend', inplace=True)
df_use['status_c'].mask(df_use['total_events'] > 0, 'Attended', inplace=True)

df_use['pre_oh'] = df_use['pre_oh'].fillna(0)
df_use['session_1'] = df_use['session_1'].fillna(0)
df_use['session_2'] = df_use['session_2'].fillna(0)
df_use['session_3'] = df_use['session_3'].fillna(0)
df_use['post_oh'] = df_use['post_oh'].fillna(0)
df_use['submitted_pr'] = df_use['submitted_pr'].fillna(0)


# code for renaming columns
# df_locinfo2 = df_locinfo2.rename(columns={'province_state': 'state-province',
#                         'Timestamp': 'timestamp',
#                        })

In [6]:
temp = df_use[['timestamp','pronouns', 'pre_oh', 'session_1', 'session_2', 'session_3',
       'post_oh', 'total_events','count_rows','status_n', 'status_c', 'submitted_pr', 'joined_discord']]

In [7]:
temp.head(5)

,timestamp,pronouns,pre_oh,session_1,session_2,session_3,post_oh,total_events,count_rows,status_n,status_c,submitted_pr,joined_discord
0,6/13/2022 18:54:55,she/her,0.0,0.0,0.0,0.0,0.0,0,1,0,Did Not Attend,0.0,1
1,7/7/2022 10:47:41,she/her,0.0,0.0,0.0,0.0,0.0,0,1,0,Did Not Attend,0.0,0
2,6/13/2022 19:56:59,she/her,1.0,1.0,0.0,0.0,0.0,2,1,1,Attended,1.0,1
3,6/20/2022 20:25:26,"she/her, they/them",1.0,0.0,1.0,0.0,0.0,2,1,1,Attended,1.0,1
4,6/22/2022 18:03:11,he/him,0.0,0.0,0.0,0.0,0.0,0,1,0,Did Not Attend,0.0,1

In [8]:
df_use.head(3)

,location,continent_o,country_o,iso_alpha,iso_num,lat,lng,timestamp,city,state-province,...,used_pymc,pymc_repo_familiar,why_in_sprint,prep_work,primary_spoken_language,language_translation,count_rows,count,status_n,status_c
0,Rochester USA,North America,United States,USD,840,43.157285,-77.615214,6/13/2022 18:54:55,Rochester,New York,...,I am not at all familiar with PyMC.,"I am familiar, I have looked at the codebase.","Looking to grow my skills as a developer, and ...",NaN,English,No,1,1,0,Did Not Attend
1,Rochester USA,North America,United States,USD,840,43.157285,-77.615214,7/7/2022 10:47:41,Rochester,New York,...,I am not at all familiar with PyMC.,I am not at all familiar with this library.,Open source data is very valuable and I'd like...,Not sure,"English, ASL",No,1,1,0,Did Not Attend
2,New York USA,North America,United States,USD,840,40.712728,-74.006015,6/13/2022 19:56:59,New York,New York,...,I am not at all familiar with PyMC.,I am not at all familiar with this library.,gain experience and learn,Yes,English,No,1,1,1,Attended

In [9]:
df_use['continent_o'].value_counts()

North America    25
Africa           18
Asia             18
Europe           12
South America     3
Name: continent_o, dtype: int64

In [10]:
df_use['status_n'].value_counts()

0    38
1    38
Name: status_n, dtype: int64

In [11]:
df_use['status_c'].value_counts()

Did Not Attend    38
Attended          38
Name: status_c, dtype: int64

In [12]:
df_use.shape

(76, 41)

In [13]:
df_use.tail(6)

,location,continent_o,country_o,iso_alpha,iso_num,lat,lng,timestamp,city,state-province,...,used_pymc,pymc_repo_familiar,why_in_sprint,prep_work,primary_spoken_language,language_translation,count_rows,count,status_n,status_c
70,Bhubaneswar India,Asia,India,INR,356,20.260296,85.839452,8/4/2022 2:13:14,Bhubaneswar,Odisha,...,I am not at all familiar with PyMC.,I am not at all familiar with this library.,To learn new things,Yes,"Hindi, English",No,1,1,0,Did Not Attend
71,Nayagarh India,Asia,India,INR,356,20.116067,85.111956,8/4/2022 6:11:12,Nayagarh,Odisha,...,I am highly experienced with PyMC.,"I am familiar, I have submitted a PR in the past",To Learn new things,Yes,English,No,1,1,0,Did Not Attend
72,Delhi India,Asia,India,INR,356,28.660058,77.156596,8/4/2022 6:58:04,Delhi,Delhi,...,I am not at all familiar with PyMC.,I have never looked at the source code.,Hacktoberfest 2020,Yes,English,No,1,1,1,Attended
73,Delhi India,Asia,India,INR,356,28.660058,77.156596,8/4/2022 11:28:28,Delhi,Delhi,...,I am not at all familiar with PyMC.,I am not at all familiar with this library.,I want to learn about open source,Yes,"Hindi, English",No,1,1,1,Attended
74,Choa Chu Kang Singapore,Asia,Singapore,SGD,702,1.385317,103.744325,8/10/2022 23:46:33,Choa Chu Kang,Choa Chu Kang,...,I am not at all familiar with PyMC.,I have never looked at the source code.,To brush up my Bayesian statistical knowledge ...,Yes,"English, Mandarin",No,1,1,0,Did Not Attend
75,Faridabad India,Asia,India,INR,356,28.403148,77.310556,8/10/2022 23:46:33,Faridabad,Haryana,...,I have used some PyMC for machine learning ana...,"I am familiar, I have looked at the codebase.",NaN,NaN,English,No,1,1,1,Attended

In [14]:
# Write out the dataframe to a file
df_use.to_csv('../data/data_derived/pymc_2022_derived.csv', index=False)

In [15]:
%load_ext watermark
%watermark -d -t -u -n -v -m -g -iv

Last updated: 2022-08-26 12:36:33

Python implementation: CPython
Python version       : 3.9.7
IPython version      : 7.25.0

Compiler    : Clang 11.1.0
OS          : Darwin
Release     : 19.6.0
Machine     : x86_64
Processor   : i386
CPU cores   : 4
Architecture: 64bit

Git hash: 5e5c7748f53923df7c844b6c8dda0adbf61fbded

pandas: 1.3.3